### ISSUE TITLE
Allow simple way to create alert triggers

### ISSUE THREAD

**Issue by grtjn** [marklogic/ml-app-deployer#437]
It seems that you can create alert configs with rules and actions, but not make it install the associated triggers automatically, like described here: https://docs.marklogic.com/REST/POST/manage/v2/databases/[id-or-name]/alert/configs

Would it be difficult to enable this? Maybe a small flag inside the alert config, or a separate file that indicates they should be created.

And for the time being, what would be the easiest workaround?

**Comment by rjrudin** [comment]
Been a while, but closing this as this endpoint - like the databases endpoint that supports an "operation" for clearing the database, reindexing the database, etc - is IMO for ad-hoc operations and not something that will typically be part of a deployment. 

If there's a need for any endpoint that requires an "operation", I think the correct approach is a custom task in ml-gradle.
