### ISSUE TITLE
Typo in toString method

### ISSUE THREAD

**Issue by ralfhergert** [marklogic/ml-app-deployer#479]
Calling toString on the RestConfig will return something like this `http://localhosthost:8000`.
The literal `host` should be removed from the referenced line.

https://github.com/marklogic/ml-app-deployer/blob/2174dd51f38a2ed958bd3697aeeb01443626f5e0/src/main/java/com/marklogic/rest/util/RestConfig.java#L128

**Comment by rjrudin** [comment]
Thanks - that's an embarrassing one! Not having tests on `toString` will do that.

**Comment by rjrudin** [comment]
Will be in 4.6.0
